resources:
- configmap.yaml
helmCharts:
- name: demo
  version: "1.0"
  namespace: demo
  valuesFile: values.yaml
  valuesMerge: merge
helmGlobals:
  chartHome: ../charts
namespace: demo
namePrefix: james-
commonLabels:
  missionlane.com/owner: snuggie12
